apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jtt4jt85w-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jtt4jt85w-java-springboot-gitops